# Generated by Django 4.2.7 on 2023-11-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerauth',
            name='owner_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='tenantauth',
            name='tenant_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
