# Generated by Django 4.2.7 on 2023-11-27 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_ownerauth_owner_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantauth',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.ownerauth'),
            preserve_default=False,
        ),
    ]
