# Generated by Django 4.2.7 on 2023-11-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_tenantauth_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantauth',
            name='mobile_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
