# Generated by Django 4.2.7 on 2023-11-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=250)),
                ('house_number', models.CharField(max_length=50)),
                ('society_name', models.CharField(max_length=250)),
                ('landmark', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
