# Generated by Django 4.2.7 on 2023-11-28 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_tenantauth_owner'),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.ownerauth'),
            preserve_default=False,
        ),
    ]
